#!/usr/bin/env bash
# permanent.sh — Hostamar boot-time restore + guard startup.
# Idempotent. Safe to run via cron @reboot OR by hand after `wsl --shutdown`.
# Goal: keep router + local fallback UP forever, never touch 100% disk, never 429.
set -uo pipefail

BUILD="/home/romel/hostamar-build"
LOG="$BUILD/permanent.log"
STATE_DIR="$BUILD/state"
mkdir -p "$STATE_DIR" "$BUILD/logs"
log() { printf '[%s] %s\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$*" >> "$LOG"; }

log "=== permanent.sh start ==="

#------- STEP 0: ensure .wslconfig caps (host RAM/CPU) ---------------
if [ ! -f "$HOME/.wslconfig" ]; then
  cat > "$HOME/.wslconfig" <<'WSL'
# generated by hostamar permanent.sh — caps resource so disk can't thrash
memory=4GB
processors=2
swap=0
WSL
  log "wslconfig: written (4GB/2cpu/noswap)"
fi

#------- STEP 1: load secrets into env WITHOUT printing ----------------
if [ -f "$BUILD/.env.docker" ]; then
  # shellcheck disable=SC1090
  set -a; . "$BUILD/.env.docker"; set +a
fi

#------- STEP 1b: ensure external docker network exists ----------------
# docker-compose.yml declares hostamar-network as external; create if missing
# so `compose up` (postgres/redis/app) doesn't abort.
if ! docker network inspect hostamar-network >/dev/null 2>&1; then
  docker network create hostamar-network >>"$LOG" 2>&1 && log "network: hostamar-network created" || log "network: create FAILED"
fi

#------- STEP 1c: ensure Postgres is up + migrations applied -----------
# Signup/login/all API routes hit prisma.customer etc. An empty/absent DB
# makes every route throw -> 500. Bring up postgres and sync schema.
if ! docker ps --format '{{.Names}}' | grep -q '^hostamar-postgres$'; then
  log "postgres: not running, bringing up via compose"
  docker compose -f "$BUILD/docker-compose.yml" up -d postgres >>"$LOG" 2>&1 || log "postgres: compose up FAILED"
  # wait for healthy (max ~40s)
  for i in $(seq 1 20); do
    if docker exec hostamar-postgres pg_isready -U hostamar >/dev/null 2>&1; then break; fi
    sleep 2
  done
fi
# Apply migrations / sync schema (idempotent). db push is drift-safe here.
if docker exec hostamar-postgres pg_isready -U hostamar >/dev/null 2>&1; then
  export DATABASE_URL="${DATABASE_URL:-postgresql://hostamar:hostamar@localhost:5432/hostamar}"
  ( cd "$BUILD" && npx prisma db push --skip-generate --accept-data-loss >>"$LOG" 2>&1 ) \
    && log "prisma: db push synced (local postgres)" || log "prisma: db push FAILED (check log)"
elif [ -n "${DATABASE_URL_CLOUD:-}" ]; then
  # Local postgres down/unavailable → fail over to cloud (Neon) so the app still runs.
  log "postgres: local NOT ready — failing over to DATABASE_URL_CLOUD (Neon)"
  export DATABASE_URL="$DATABASE_URL_CLOUD"
  log "prisma: using cloud DB (skipping db push on managed Neon — schema managed separately)"
else
  log "postgres: NOT ready AND no DATABASE_URL_CLOUD — routes will 500 until DB up"
fi

#------- STEP 2: ensure host Ollama is running ------------------------
if ! curl -s --max-time 3 http://localhost:11434/api/tags >/dev/null 2>&1; then
  log "ollama: host down, starting..."
  OLLAMA_KEEP_ALIVE=5m nohup ollama serve >/tmp/ollama.log 2>&1 &
  sleep 4
fi
if curl -s --max-time 3 http://localhost:11434/api/tags >/dev/null 2>&1; then
  log "ollama: up — loading locked models (idempotent cp)"
  python3 - <<'PY'
import json, subprocess, sys
locked = json.load(open('/home/romel/hostamar-build/perma-locked.json'))
for m in locked.get('models', []):
    src, dst = None, None
    if ' cp ' in m['via']:
        parts = m['via'].split()
        # ['ollama','cp',src,dst]
        if len(parts) >= 4: src, dst = parts[2], parts[3]
    if not src or not dst: continue
    res = subprocess.run(['ollama','list'], capture_output=True, text=True)
    if dst in res.stdout:
        continue
    subprocess.run(['ollama','cp', src, dst], check=False)
print('locked models ensured')
PY
else
  log "ollama: STILL DOWN after boot attempt — local fallback unavailable"
fi

#------- STEP 3: bring up litellm-play (the dead container) ----------
cd "$BUILD"
docker rm -f litellm-try >/dev/null 2>&1 || true   # stale duplicate

if ! docker ps --format '{{.Names}}' | grep -q '^litellm-play$'; then
  docker rm -f litellm-play >/dev/null 2>&1 || true
  log "litellm-play: launching via guard entrypoint..."
  docker run -d \
    --name litellm-play \
    --restart unless-stopped \
    -p 4000:4000 \
    -v "$BUILD/litellm-config.final.yaml:/tmp/cfg.yaml:ro" \
    -v "$BUILD/guard:/tmp/guard:ro" \
    -v "$BUILD/state/guard_history.db:/tmp/guard_history.db" \
    -e PYTHONPATH=/tmp/guard:/tmp \
    -e NVIDIA_API_KEY="${NVIDIA_API_KEY:-}" \
    -e KILOCODE_API_KEY="${KILOCODE_API_KEY:-}" \
    -e KILOCODE_BASE_URL="${KILOCODE_BASE_URL:-https://api.kilo.ai/api/gateway}" \
    -e TG_DB=/tmp/guard_history.db \
    -e TG_ARCHIVE_PATH=/tmp/guard_archive.jsonl \
    --add-host host.docker.internal:host-gateway \
    --entrypoint /bin/bash \
    ghcr.io/berriai/litellm:main-latest \
    /tmp/guard/entrypoint-litellm.sh >>"$LOG" 2>&1
  sleep 8
else
  log "litellm-play: already up"
fi

#------- STEP 4: bring docker stack via canonical compose ---------------
if [ -f "$BUILD/docker-compose.yml" ]; then
  log "stack: docker compose up -d (canonical)"
  docker compose -f "$BUILD/docker-compose.yml" up -d --remove-orphans >>"$LOG" 2>&1 || \
    log "stack: compose up FAILED (see log)"
fi

#------- STEP 5: snapshot disk + containers ----------------------------
{
  echo "--- df ---"; df -h / /mnt/c 2>/dev/null | head -2
  echo "--- docker ps ---"; docker ps --format '{{.Names}}\t{{.Status}}' | head -20
  echo "--- ollama ---"; curl -s --max-time 3 http://localhost:11434/api/tags | head -c 200
  echo "--- router ---"; curl -s --max-time 4 http://localhost:4000/v1/models | head -c 300
} >> "$LOG"

#------- STEP 6: append to the permanent history SQLite ---------------
python3 - <<'PY' || true
import sqlite3, time, os, subprocess, json, datetime
DB = '/home/romel/hostamar-build/state/run_history.db'
sqlite3.connect(DB).execute("""CREATE TABLE IF NOT EXISTS runs(
  ts TEXT, wsl_mem_limit TEXT, ollama_up INT, router_up INT, n_containers INT,
  disk_root_pct INT, disk_c_pct INT, models_loaded TEXT)""")
ts = datetime.datetime.now(datetime.timezone.utc).isoformat()
def cols():
    try:
        c = open(os.path.expanduser('~/.wslconfig')).read()
        return [l for l in c.splitlines() if l.startswith('memory')][0]
    except: return '?'
ollama_up = 1 if subprocess.run(['curl','-sf','--max-time','3','http://localhost:11434/api/tags'], capture_output=True).returncode==0 else 0
router_up = 1 if subprocess.run(['curl','-sf','--max-time','4','http://localhost:4000/v1/models'], capture_output=True).returncode==0 else 0
ps = subprocess.run(['docker','ps','--format','{{.Names}}'], capture_output=True, text=True).stdout.strip().splitlines()
def pct(m):
    r = subprocess.run(['bash','-c',"df %s | awk 'NR==2{print $5}' | tr -d '%%'" % m], capture_output=True, text=True).stdout.strip()
    return int(r) if r.isdigit() else -1
sqlite3.connect(DB).execute(
    "INSERT INTO runs VALUES (?,?,?,?,?,?,?,?)",
    (ts, cols(), ollama_up, router_up, len(ps),
     pct('/'), pct('/mnt/c'), ','.join(ps)))
print("history row written")
PY

log "=== permanent.sh done ==="
