-- Add columns to Preview
ALTER TABLE "Preview" ADD COLUMN IF NOT EXISTS "videoId" TEXT;
ALTER TABLE "Preview" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "Preview" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Preview" ADD COLUMN IF NOT EXISTS "duration" INTEGER;
ALTER TABLE "Preview" ADD COLUMN IF NOT EXISTS "prompt" TEXT;
ALTER TABLE "Preview" ADD COLUMN IF NOT EXISTS "style" TEXT;
ALTER TABLE "Preview" ADD COLUMN IF NOT EXISTS "renderStatus" TEXT;
ALTER TABLE "Preview" ADD COLUMN IF NOT EXISTS "renderError" TEXT;
ALTER TABLE "Preview" ADD COLUMN IF NOT EXISTS "videoUrl" TEXT;

-- Add columns to Subtitle
ALTER TABLE "Subtitle" ADD COLUMN IF NOT EXISTS "language" TEXT DEFAULT 'bn';

-- Add missing columns to Customer
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "stage" TEXT DEFAULT 'lead';
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "source" TEXT DEFAULT 'website';
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "score" INTEGER DEFAULT 0;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "credits" INTEGER DEFAULT 0;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "referralCode" TEXT;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "referredBy" TEXT;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "referralBonus" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "balance" DOUBLE PRECISION DEFAULT 0;

-- Tighten Customer.credits to NOT NULL with default
UPDATE "Customer" SET credits = 0 WHERE credits IS NULL;
ALTER TABLE "Customer" ALTER COLUMN credits SET NOT NULL;
ALTER TABLE "Customer" ALTER COLUMN credits SET DEFAULT 0;