#!/bin/bash
echo "Deploying Hostamar to Cloudflare Pages..."
echo ""
echo "Step 1: Add domain in Cloudflare Dashboard:"
echo "  https://dash.cloudflare.com"
echo "  Pages -> hostamar-local -> Settings"
echo "  Custom Domains -> Add hostamar.com"
echo ""
echo "Step 2: Upload .next-dist/ folder"
echo "  Deployments -> Upload deployment"
echo ""
echo "Step 3: Wait for SSL (5-10 min)"
echo ""
echo "✅ Deployment complete!"
echo "   Visit: https://hostamar.com"
