'use client'
import { useState } from "react"
import { Globe, Check, ArrowUpRight, Star, ShieldCheck, Zap, Server, Database, Lock } from "lucide-react"

export default function HostingPage(){
  const [openFaq, setOpenFaq] = useState<number|null>(0)
  return (
    <div className="min-h-screen bg-[#FCFCF9] text-zinc-900 antialiased">
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;600;700&family=Inter:wght@400;500;600&display=swap'); h1,h2,h3{font-family:"Hind Siliguri",sans-serif} body{font-family:Inter,sans-serif}`}</style>
      <div className="w-full bg-zinc-900 text-zinc-100 text-[13px]"><div className="mx-auto max-w-[1180px] px-6 h-9 flex items-center justify-between"><span>5GB Free • BDIX • 99.9% SLA</span><span>bKash • Nagad • Rocket</span></div></div>
      <header className="sticky top-0 z-40 backdrop-blur bg-[#FCFCF9]/80 border-b"><div className="mx-auto max-w-[1180px] px-6 h-16 flex items-center justify-between"><div className="flex items-center gap-2 font-bold"><div className="h-8 w-8 rounded-xl bg-[#0E7C3A] text-white grid place-items-center"><Server className="h-4 w-4"/></div>Hostamar /hosting</div><a href="https://hostamar.com/generate" className="h-9 px-4 rounded-full bg-zinc-900 text-white text-sm inline-flex items-center gap-1">ফ্রি হোস্টিং শুরু করুন <ArrowUpRight className="h-4 w-4"/></a></div></header>
      <section className="mx-auto max-w-[1180px] px-6 py-16 grid md:grid-cols-2 gap-10 items-center">
        <div><div className="inline-flex border px-3 py-1 rounded-full text-xs">cPanel ছাড়া আধুনিক</div><h1 className="mt-4 text-4xl md:text-5xl font-bold leading-tight">cPanel ছাড়া আধুনিক হোস্টিং, <span className="text-[#0E7C3A]">bKash দিয়ে পেমেন্ট</span></h1><p className="mt-4 opacity-70 leading-relaxed">ঢাকা CDN, NVMe SSD, ৯৯.৯% আপটাইম, বাংলা কন্ট্রোল প্যানেল। ExonHost এর পুরানো cPanel এর বদলে Vercel এর মতো অভিজ্ঞতা।</p><div className="mt-6 flex gap-3"><a href="https://hostamar.com/generate" className="h-11 px-6 rounded-full bg-[#0E7C3A] text-white inline-flex items-center">ফ্রি শুরু করুন</a><a href="#compare" className="h-11 px-6 rounded-full border inline-flex items-center">তুলনা দেখুন</a></div></div>
        <div className="rounded-2xl bg-zinc-900 text-white p-6 shadow-2xl"><div className="text-xs opacity-60">hostamar.com control panel</div><div className="mt-4 grid grid-cols-3 gap-3 text-center"><div className="bg-white/10 rounded-xl p-3"><div className="text-2xl font-bold">5GB</div><div className="text-xs opacity-60">Free</div></div><div className="bg-white/10 rounded-xl p-3"><div className="text-2xl font-bold">99.9%</div><div className="text-xs opacity-60">Uptime</div></div><div className="bg-white/10 rounded-xl p-3"><div className="text-2xl font-bold">20ms</div><div className="text-xs opacity-60">BD Ping</div></div></div><div className="mt-4 bg-white text-zinc-900 rounded-xl p-4"><div className="flex justify-between text-sm"><span>✓ WordPress 1-click</span><span>✓ Node.js</span></div><div className="mt-2 flex justify-between text-sm"><span>✓ Free SSL</span><span>✓ Daily Backup</span></div></div></div>
      </section>
      <section id="compare" className="mx-auto max-w-[1180px] px-6 py-12"><h2 className="text-2xl font-bold">ExonHost vs Hostamar</h2><div className="mt-6 overflow-x-auto border rounded-2xl"><table className="w-full text-sm"><thead className="bg-zinc-50"><tr><th className="p-3 text-left">Feature</th><th className="p-3">ExonHost</th><th className="p-3 bg-[#0E7C3A]/10">Hostamar</th></tr></thead><tbody><tr className="border-t"><td className="p-3">bKash Auto Payment</td><td className="p-3 text-center">Manual</td><td className="p-3 text-center font-semibold text-[#0E7C3A]">Auto ✓</td></tr><tr className="border-t"><td className="p-3">Bangla Panel</td><td className="p-3 text-center">No</td><td className="p-3 text-center font-semibold">Yes ✓</td></tr><tr className="border-t"><td className="p-3">Node.js Support</td><td className="p-3 text-center">Limited</td><td className="p-3 text-center font-semibold">Full ✓</td></tr></tbody></table></div></section>
      <section className="mx-auto max-w-[1180px] px-6 py-12 grid md:grid-cols-3 gap-4"><div className="rounded-2xl border p-6"><Zap className="h-5 w-5"/><h3 className="mt-3 font-semibold">One-click WordPress</h3><p className="text-sm opacity-60 mt-1">Vercel like experience</p></div><div className="rounded-2xl border p-6"><Globe className="h-5 w-5"/><h3 className="mt-3 font-semibold">Dhaka CDN</h3><p className="text-sm opacity-60 mt-1">20ms BD ping</p></div><div className="rounded-2xl border p-6"><Lock className="h-5 w-5"/><h3 className="mt-3 font-semibold">Free SSL + Backup</h3><p className="text-sm opacity-60 mt-1">Daily backup</p></div></section>
      <section className="mx-auto max-w-[1180px] px-6 py-12"><div className="rounded-2xl bg-zinc-900 text-white p-8 text-center"><h2 className="text-3xl font-bold">ExonHost থেকে ফ্রি মাইগ্রেশন ৩০ মিনিটে</h2><p className="opacity-70 mt-2">1. ডোমেইন দিন 2. আমরা কপি করি 3. Live</p><a href="https://hostamar.com/generate" className="mt-6 inline-flex h-11 px-6 rounded-full bg-white text-zinc-900 font-semibold items-center">মাইগ্রেশন শুরু করুন</a></div></section>
      <section className="mx-auto max-w-[1180px] px-6 py-12 grid md:grid-cols-3 gap-6"><div className="border rounded-2xl p-6"><h3 className="font-bold">Free</h3><div className="text-3xl font-bold mt-2">৳0</div><ul className="mt-4 text-sm space-y-2 opacity-70"><li>✓ 5GB SSD</li><li>✓ 1 Website</li></ul></div><div className="border-2 border-[#0E7C3A] rounded-2xl p-6 bg-[#0E7C3A]/5"><div className="text-xs bg-[#0E7C3A] text-white px-2 py-1 rounded-full inline">Popular</div><h3 className="font-bold mt-2">Starter</h3><div className="text-3xl font-bold mt-2">৳800<span className="text-sm font-normal">/mo</span></div><ul className="mt-4 text-sm space-y-2"><li>✓ 10GB NVMe</li><li>✓ 10 Websites</li><li>✓ bKash Auto</li></ul></div><div className="border rounded-2xl p-6"><h3 className="font-bold">Business</h3><div className="text-3xl font-bold mt-2">৳2000</div><p className="text-xs mt-2 opacity-60">Video Business কিনলে Hosting Free</p></div></section>
      <footer className="border-t py-10 text-center text-sm opacity-60">© Hostamar • Made in Bangladesh • bKash Nagad Rocket</footer>
    </div>
  )
}
