export const FREESTACK_REPOS = [
  { id:1, name:'AutoHedge', github:'The-Swarm-Corporation/AutoHedge', url:'https://github.com/The-Swarm-Corporation/AutoHedge', replaces:'Quant Trading Desk / Hedge Fund', price:'$10k+/mo', what:'4 AI Agent Director Quant Risk Manager Execution দিয়ে Solana autonomous hedge fund pip install autohedge live trading', install:'pip install autohedge', category:'Trading' },
  { id:2, name:'Vibe-Trading', github:'HKUDS/Vibe-Trading', url:'https://github.com/HKUDS/Vibe-Trading', replaces:'Trading Terminal + Analyst', price:'$500/mo', what:'DAG-based multi-agent trading floor 77 finance skill 29 agent swarm 452+ alpha Bull vs Bear debate', install:'git clone HKUDS/Vibe-Trading', category:'Trading' },
  { id:3, name:'Fincept Terminal', github:'Fincept-Corporation/FinceptTerminal', url:'https://github.com/Fincept-Corporation/FinceptTerminal', replaces:'Bloomberg Terminal', price:'$27,000/year', what:'ল্যাপটপে চলে 37 AI investor agent 100+ data connector CFA-level analytics Wall Street terminal free alt', install:'git clone Fincept-Corporation/FinceptTerminal', category:'Finance' },
  { id:4, name:'LibreChat', github:'danny-avila/LibreChat', url:'https://github.com/danny-avila/LibreChat', replaces:'ChatGPT Plus', price:'$20/mo', what:'নিজের সার্ভারে hosted ChatGPT clone ChatGPT Claude Gemini Groq own API key', install:'docker run -p 3080:3080 ghcr.io/danny-avila/librechat', category:'AI Chat' },
  { id:5, name:'Open Generative AI', github:'Anil-matcha/Open-Generative-AI', url:'https://github.com/Anil-matcha/Open-Generative-AI', replaces:'Midjourney + Runway + Sora', price:'$60+/mo', what:'200+ models Flux Midjourney Kling Sora Veo one dashboard text-to-image video lip-sync', install:'git clone Anil-matcha/Open-Generative-AI', category:'Video OS' },
  { id:6, name:'Open-LLM-VTuber', github:'Open-LLM-VTuber/Open-LLM-VTuber', url:'https://github.com/Open-LLM-VTuber/Open-LLM-VTuber', replaces:'AI Companion App', price:'$10+/mo', what:'Offline voice AI friend screen see Live2D avatar', install:'git clone Open-LLM-VTuber/Open-LLM-VTuber', category:'AI Companion' },
  { id:7, name:'Claude Ads', github:'AgriciDaniel/claude-ads', url:'https://github.com/AgriciDaniel/claude-ads', replaces:'Agency Ad Audit', price:'$4,000/mo', what:'Claude Code skill Google Meta YouTube LinkedIn TikTok Microsoft Ads 190+ checks 6 agents parallel health score', install:'claude-code skill install claude-ads', category:'Marketing' },
  { id:8, name:'Agentic Inbox', github:'cloudflare/agentic-inbox', url:'https://github.com/cloudflare/agentic-inbox', replaces:'Superhuman', price:'$30/mo', what:'Cloudflare Workers AI email triage reply draft Durable Object isolated', install:'wrangler deploy', category:'Email' },
  { id:9, name:'Camofox', github:'jo-inc/camofox-browser', url:'https://github.com/jo-inc/camofox-browser', replaces:'Stealth Scraping API', price:'$200/mo', what:'AI agents anti-detection browser Cloudflare bot bypass Puppeteer Playwright drop-in', install:'npm i camofox-browser', category:'Browser' },
  { id:10, name:'Hyperframes', github:'heygen-com/hyperframes', url:'https://github.com/heygen-com/hyperframes', replaces:'Paid Video Render SaaS', price:'$100+/mo', what:'Agent HTML/CSS/JS deterministic MP4 headless Chrome FFmpeg GSAP Lottie Three.js', install:'npm i @heygen/hyperframes', category:'Video Render' },
] as const;
