/**
 * Bangladesh-first video prompt templates for Hostamar AI Video.
 * 50+ templates across 10 categories — each optimised for Bengali + BD context.
 */
export interface VideoTemplate {
  id: string
  label: string
  labelBn: string        // Bengali label
  icon: string
  category: string
  categoryBn: string
  prompt: string         // English prompt sent to AI
  promptBn: string       // Bengali context description
  duration?: number      // recommended duration in seconds
  aspectRatio?: '16:9' | '9:16' | '1:1'
  tags?: string[]
}

export const VIDEO_TEMPLATES: VideoTemplate[] = [
  // ── 🛍️ Facebook Shop Ads ────────────────────────────────────────────────
  {
    id: 'cloth-demonstration',
    label: 'Cloth / Fashion Showcase',
    labelBn: 'কাপড় ও ফ্যাশন শোকেস',
    icon: '👗',
    category: 'facebook-shop',
    categoryBn: 'ফেসবুক শপ বিজ্ঞাপন',
    prompt: 'A young Bengali woman walking through Dhaka streets in a elegant jamdani saree, camera slowly revealing the intricate fabric design and pattern, soft natural lighting, cinematic style, 4K.',
    promptBn: 'ঢাকার রাস্তায় এক তরুণী জামদানি শাড়ি পরে হাঁটছেন, ক্যামেরা ধীরে ধীরে কাপড়ের ডিজাইন দেখাচ্ছে।',
    duration: 15,
    aspectRatio: '9:16',
    tags: ['fashion', 'saree', 'Dhaka'],
  },
  {
    id: 'ecommerce-unboxing',
    label: 'E-commerce Unboxing',
    labelBn: 'ই-কমার্স আনবক্সিং',
    icon: '📦',
    category: 'facebook-shop',
    categoryBn: 'ফেসবুক শপ বিজ্ঞাপন',
    prompt: 'A customer opens a cardboard box with excitement, reveals a beautifully packaged product, holds it up to camera smiling, bold text overlay: "Surprise Gift!", warm indoor lighting.',
    promptBn: 'একজন গ্রাহক বাক্স খুলছেন, প্রোডাক্ট বের করছেন হাসিমুখে।',
    duration: 10,
    aspectRatio: '9:16',
    tags: ['unboxing', 'review'],
  },
  {
    id: 'flash-sale-banner',
    label: 'Flash Sale Countdown',
    labelBn: 'ফ্ল্যাশ সেল কাউন্টডাউন',
    icon: '⏰',
    category: 'facebook-shop',
    categoryBn: 'ফেসবুক শপ বিজ্ঞাপন',
    prompt: 'Street view with large banner "50% OFF", countdown timer ticking down, Bengali voice-over energy tone, vibrant colors, dynamic camera zoom effect.',
    promptBn: 'স্ট্রিট ভিউতে বড় ব্যানার "৫০% ছাড়", কাউন্টডাউন টাইমার টিকটিক করছে।',
    duration: 15,
    aspectRatio: '9:16',
    tags: ['sale', 'countdown', 'bangla'],
  },
  {
    id: 'before-after-saree',
    label: 'Before / After Saree Drape',
    labelBn: 'শাড়ি পরানোর আগে-পরে',
    icon: '💃',
    category: 'facebook-shop',
    categoryBn: 'ফেসবুক শপ বিজ্ঞাপন',
    prompt: 'Split screen: left side a plain fabric, right side the same fabric styled as an elegant saree on a model, smooth transition animation, text overlay in Bengali: "এভাবে পরুন!", warm golden lighting.',
    promptBn: 'স্প্লিট স্ক্রিন: একদিকে সাদা কাপড়, অন্যদিকে সেই কাপড় শাড়ি হয়ে এক মডেলের গায়ে।',
    duration: 12,
    aspectRatio: '9:16',
    tags: ['saree', 'transformation', 'bangla'],
  },
  {
    id: 'customer-review-card',
    label: 'Verified Customer Review Card',
    labelBn: 'ভেরিফাইড গ্রাহক রিভিউ কার্ড',
    icon: '⭐',
    category: 'facebook-shop',
    categoryBn: 'ফেসবুক শপ বিজ্ঞাপন',
    prompt: 'A smiling Bengali woman in her home holding a product, animated quote box with Bengali text "সেরা কোয়ালিটি!", star rating animation, trust badge icons, soft home lighting.',
    promptBn: 'বাড়িতে এক বাংলা নারী প্রোডাক্ট হাতে হাসিমুখে, অ্যানিমেটেড কোট বক্সে "সেরা কোয়ালিটি!"।',
    duration: 10,
    aspectRatio: '1:1',
    tags: ['testimonial', 'review', 'bangla'],
  },
  // ── 📚 Educational ───────────────────────────────────────────────────────
  {
    id: 'english-word-learn',
    label: 'English Word of the Day',
    labelBn: 'ইংরেজি শব্দ শেখা',
    icon: '📖',
    category: 'education',
    categoryBn: 'শিক্ষা কন্টেন্ট',
    prompt: 'White board showing an English word with Bengali meaning and pronunciation, character animating the word pronunciation, each word stays 3 seconds, clean educational style.',
    promptBn: 'সাদা বোর্ডে ইংরেজি শব্দ, বাংলা অর্থ ও উচ্চারণ দেখাচ্ছে, ক্যারেক্টার শব্দটি উচ্চারণ করছে।',
    duration: 20,
    aspectRatio: '9:16',
    tags: ['english', 'learning', 'bangla'],
  },
  {
    id: 'math-problem-step',
    label: 'Math Problem Step-by-Step',
    labelBn: 'গণিত সমস্যা সমাধান',
    icon: '🔢',
    category: 'education',
    categoryBn: 'শিক্ষা কন্টেন্ট',
    prompt: 'Screen recording style: a math problem being solved step by step with animated handwriting, Bengali voice-over explaining each step, clean white background.',
    promptBn: 'স্ক্রিন রেকর্ডিং স্টাইল: গাণিতিক সমস্যার ধাপে ধাপে সমাধান, বাংলা ভয়েসওভার।',
    duration: 30,
    aspectRatio: '16:9',
    tags: ['math', 'education', 'bangla'],
  },
  {
    id: 'iq-fact-card',
    label: 'IQ Fun Fact Reel',
    labelBn: 'আইকিউ ফান ফ্যাক্ট রিল',
    icon: '🧠',
    category: 'education',
    categoryBn: 'শিক্ষা কন্টেন্ট',
    prompt: 'Animated brain icon, fact text appearing letter by letter in Bengali, colorful gradient background, engaging music, 15 second fun fact about science or geography.',
    promptBn: 'অ্যানিমেটেড ব্রেইন আইকন, ফ্যাক্ট টেক্সট বাংলায় অক্ষরে অক্ষরে দেখা যাচ্ছে।',
    duration: 15,
    aspectRatio: '9:16',
    tags: ['facts', 'science', 'bangla'],
  },
  {
    id: 'sciccer-trick-hack',
    label: 'Scissor Trick / Life Hack',
    labelBn: 'কাঁচি ট্রিক / লাইফ হ্যাক',
    icon: '✂️',
    category: 'education',
    categoryBn: 'শিক্ষা কন্টেন্ট',
    prompt: 'Close-up hands showing a scissors trick or daily life hack, step by step demonstration, Bengali text annotations, bright natural lighting, fast-paced editing.',
    promptBn: 'ক্লোজ-আপ হ্যান্ডস কাঁচি ট্রিক দেখাচ্ছে, ধাপে ধাপে ডেমো, বাংলা টেক্সট অ্যানোটেশন।',
    duration: 20,
    aspectRatio: '9:16',
    tags: ['hack', 'trick', 'DIY'],
  },
  // ── 🕌 Religious & Spiritual ─────────────────────────────────────────────
  {
    id: 'surah-tilawat',
    label: 'Surah Tilawat',
    labelBn: 'সূরা তিলাওয়াত',
    icon: '🕌',
    category: 'religious',
    categoryBn: 'ধর্মীয় ও আধ্যাত্মিক',
    prompt: 'Deep green background with Arabic verse, Bengali translation below, soft nasheed music playing, gentle fade transitions, golden light accents, 60 seconds.',
    promptBn: 'গাঢ় সবুজ ব্যাকগ্রাউন্ডে আরবি আয়াত, নিচে বাংলা অনুবাদ, নরম নাশিদ ব্যাকগ্রাউন্ড।',
    duration: 60,
    aspectRatio: '9:16',
    tags: ['religious', 'quran', 'bangla'],
  },
  {
    id: 'eid-greeting',
    label: 'Eid Greeting Card',
    labelBn: 'ঈদ শুভেচ্ছা কার্ড',
    icon: '🌙',
    category: 'religious',
    categoryBn: 'ধর্মীয় ও আধ্যাত্মিক',
    prompt: 'Moon imagery, flower animation, handwritten Bengali text "ঈদ মুবারক", warm celebratory music, festive colors purple and gold, gentle floating particles.',
    promptBn: 'চাঁদের ছবি, ফুলের অ্যানিমেশন, হাতে লেখা বাংলায় "ঈদ মুবারক"।',
    duration: 10,
    aspectRatio: '1:1',
    tags: ['eid', 'greeting', 'bangla'],
  },
  {
    id: 'puja-thali-decor',
    label: 'Puja Thali Decoration',
    labelBn: 'পূজার থালি সাজানো',
    icon: '🪔',
    category: 'religious',
    categoryBn: 'ধর্মীয় ও আধ্যাত্মিক',
    prompt: 'Close-up of a beautifully decorated puja thali with diya, flowers, and puja items, camera slowly panning across the arrangement, diya flames flickering, warm golden tones.',
    promptBn: 'সুন্দরভাবে সাজানো পূজার থালি, দিয়া, ফুল, ক্যামেরা ধীরে ঘুরছে, উষ্ণ সোনালি আলো।',
    duration: 20,
    aspectRatio: '9:16',
    tags: ['puja', 'thali', 'bangla'],
  },
  {
    id: 'ramadan-tarawih',
    label: 'Ramadan Tarawih Night',
    labelBn: 'রমজান তারাবিহ রাত',
    icon: '📿',
    category: 'religious',
    categoryBn: 'ধর্মীয় ও আধ্যাত্মিক',
    prompt: 'Night sky with crescent moon over a mosque silhouette, soft prayer sounds in background, Bengali text: "রমজান মাসের শুভ কামনা", gentle star animation.',
    promptBn: 'চাঁদের আকাশ, মসজিদের ছায়া, নরম আজান শব্দ, বাংলা টেক্সট।',
    duration: 15,
    aspectRatio: '16:9',
    tags: ['ramadan', 'mosque', 'bangla'],
  },
  // ── 🍳 Recipe & Food ─────────────────────────────────────────────────────
  {
    id: 'one-minute-snack',
    label: '1-Minute Snack Recipe',
    labelBn: '১ মিনিটের নাস্তার রেসিপি',
    icon: '🍳',
    category: 'food',
    categoryBn: 'রেসিপি ও ফুড',
    prompt: 'Oven-top shot, hot samosas on a steel plate, sauce being poured in slow motion, close-up of crispy texture, Bengali text: "১০ মিনিটে বানানো!", appetizing warm colors.',
    promptBn: 'ওভেন-টপ শট, থালায় গরম গরম সিঙ্গারা, সস ঢালছে, ক্লোজ-আপ।',
    duration: 15,
    aspectRatio: '9:16',
    tags: ['recipe', 'snack', 'bangla'],
  },
  {
    id: 'chai-stall-reel',
    label: 'Chai Stall Aesthetic',
    labelBn: 'চায়ের দোকান রিল',
    icon: '☕',
    category: 'food',
    categoryBn: 'রেসিপি ও ফুড',
    prompt: 'Footpath chai stall, tea being poured from height into cup, steam rising, cup held up to camera, Bengali folk music in background, 30 second aesthetic shot.',
    promptBn: 'ফুটপাথের চায়ের দোকান, উচ্চতা থেকে কাপে চা ঢালা, কাপের ধোঁয়া উঠছে।',
    duration: 30,
    aspectRatio: '9:16',
    tags: ['chai', 'aesthetic', 'bangla'],
  },
  {
    id: 'biriani-dum',
    label: 'Kacchi Biriani Close-Up',
    labelBn: 'কাচ্চি বিরিয়ানি ক্লোজ-আপ',
    icon: '🍛',
    category: 'food',
    categoryBn: 'রেসিপি ও ফুড',
    prompt: 'Steaming kacchi biriani pot being opened, steam billowing out, rice being scoop-served with dam keema, close-up of the saffron rice color and texture, food photography style.',
    promptBn: 'বাষ্প উঠছে কাচ্চি বিরিয়ানির হাড়িখানা, ধীরে ধীরে পরিবেশন, ক্লোজ-আপ।',
    duration: 15,
    aspectRatio: '16:9',
    tags: ['biriani', 'food', 'bangla'],
  },
  {
    id: 'street-food-tour',
    label: 'Street Food Tour Reel',
    labelBn: 'স্ট্রিট ফুড ট্যুর রিল',
    icon: '🍢',
    category: 'food',
    categoryBn: 'রেসিপি ও ফুড',
    prompt: 'Satisfying montage of Bengali street foods — beguni, chotpoti, fuchka, bhuna khichuri — each clip 3 seconds with text overlay naming the dish, upbeat Bengali music, vibrant street colors.',
    promptBn: 'বাংলা স্ট্রিট ফুড মন্টেজ — বেগুনি, চটপটি, ফুচকা, ভুনা খিচুড়ি — প্রতিটি ৩ সেকেন্ড।',
    duration: 30,
    aspectRatio: '9:16',
    tags: ['streetfood', 'reel', 'bangla'],
  },
  // ── 💼 Business & Marketing ───────────────────────────────────────────────
  {
    id: 'restaurant-intro',
    label: 'Restaurant Introduction',
    labelBn: 'রেস্তোরাঁ পরিচিতি',
    icon: '🍽️',
    category: 'business',
    categoryBn: 'ব্যবসা ও মার্কেটিং',
    prompt: 'Drone shot over Gulshan restaurant, interior shots of clients dining, Bengali voice-over: "২০ বছরের স্বাদ, এখন আপনার দোরগোড়ায়", logo animation, warm restaurant lighting.',
    promptBn: 'গুলশানের রেস্তোরাঁ, ড্রোন শট, ক্লায়েন্টরা খাচ্ছেন, বাংলা ভয়েসওভার।',
    duration: 30,
    aspectRatio: '16:9',
    tags: ['restaurant', 'intro', 'bangla'],
  },
  {
    id: 'startup-pitch-3slides',
    label: 'Startup Pitch 3 Slides',
    labelBn: 'স্টার্টআপ পিচ ৩ স্লাইড',
    icon: '🚀',
    category: 'business',
    categoryBn: 'ব্যবসা ও মার্কেটিং',
    prompt: 'Professional typography, Bengali and English text, 3 slides animated: Problem → Solution → Contact. Modern font, blue and white color scheme, 1 minute duration.',
    promptBn: 'প্রফেশনাল ফন্ট, বাংলা + ইংরেজি টেক্সট, ৩ স্লাইড: সমস্যা → সমাধান → যোগাযোগ।',
    duration: 60,
    aspectRatio: '16:9',
    tags: ['startup', 'pitch', 'bangla'],
  },
  {
    id: 'mega-sale-announcement',
    label: 'Mega Sale Announcement',
    labelBn: 'মেগা সেল অ্যানাউন্সমেন্ট',
    icon: '🏷️',
    category: 'business',
    categoryBn: 'ব্যবসা ও মার্কেটিং',
    prompt: 'Dynamic text animation, Bengali text "সেরা অফার এসেছে!", prices slashed with red strikethrough animation, product carousel, upbeat energetic music, shop owners smiling.',
    promptBn: 'ডায়নামিক টেক্সট অ্যানিমেশন, "সেরা অফার এসেছে!", দাম কাটছে, প্রোডাক্ট ক্যারাউজেল।',
    duration: 15,
    aspectRatio: '16:9',
    tags: ['sale', 'marketing', 'bangla'],
  },
  {
    id: 'new-product-teaser',
    label: 'New Product Teaser',
    labelBn: 'নতুন প্রোডাক্ট টিজার',
    icon: '✨',
    category: 'business',
    categoryBn: 'ব্যবসা ও মার্কেটিং',
    prompt: 'Product reveal in darkness, spotlight on item, glitch animation, Bengali text "এল নতুন", dramatic music build-up, logo stamp, 10 second teaser.',
    promptBn: 'অন্ধকারে প্রোডাক্ট রিভিল, স্পটলাইট, গ্লিচ অ্যানিমেশন, "এল নতুন", ড্রামাটিক মিউজিক।',
    duration: 10,
    aspectRatio: '9:16',
    tags: ['teaser', 'product', 'bangla'],
  },
  // ── 🎭 Entertainment & Meme ─────────────────────────────────────────────
  {
    id: 'comedy-relatable',
    label: 'Relatable Comedy Scene',
    labelBn: 'রিলেটেবল কমেডি সিন',
    icon: '😂',
    category: 'entertainment',
    categoryBn: 'বিনোদন ও মিম',
    prompt: 'Short comedic scene depicting a relatable Bengali daily life moment — student avoiding homework, uncle giving unwanted advice — exaggerated expressions, funny background music.',
    promptBn: 'হাস্যরসাত্মক সিন — ছাত্র হোমওয়ার্ক এড়াচ্ছে, চাচা অবাঞ্ছিত পরামর্শ দিচ্ছে।',
    duration: 20,
    aspectRatio: '9:16',
    tags: ['comedy', 'relatable', 'bangla'],
  },
  {
    id: 'trending-sound-dance',
    label: 'Trending Sound Dance Reel',
    labelBn: 'ট্রেন্ডিং সাউন্ড ডান্স রিল',
    icon: '💃',
    category: 'entertainment',
    categoryBn: 'বিনোদন ও মিম',
    prompt: 'Bengali trending sound plays, dancer performing in colorful urban street setting, text overlay of song lyrics, hashtag animation, vibrant energetic colors.',
    promptBn: 'বাংলা ট্রেন্ডিং সাউন্ড বাজছে, ডান্সার স্ট্রিট সেটিংয়ে পারফর্ম করছেন।',
    duration: 30,
    aspectRatio: '9:16',
    tags: ['dance', 'reel', 'trending'],
  },
  // ── 🏋️ Fitness & Health ────────────────────────────────────────────────
  {
    id: 'home-workout-guide',
    label: 'Home Workout Guide',
    labelBn: 'বাড়িতে ওয়ার্কআউট গাইড',
    icon: '🏋️',
    category: 'fitness',
    categoryBn: 'ফিটনেস ও স্বাস্থ্য',
    prompt: 'Fit Bengali trainer demonstrating exercise in a home setting, countdown timer overlay 30s per exercise, Bengali instruction text, clean bright room, encouraging energy.',
    promptBn: 'ফিট বাংলা ট্রেনার বাড়িতে এক্সারসাইজ দেখাচ্ছেন, কাউন্টডাউন টাইমার, বাংলা নির্দেশনা।',
    duration: 60,
    aspectRatio: '9:16',
    tags: ['workout', 'fitness', 'bangla'],
  },
  {
    id: 'health-tip-card',
    label: 'Daily Health Tip Card',
    labelBn: 'দৈনিক স্বাস্থ্য টিপস কার্ড',
    icon: '💊',
    category: 'fitness',
    categoryBn: 'ফিটনেস ও স্বাস্থ্য',
    prompt: 'Calm green gradient background, animated medical icon, Bengali health tip text appearing letter by letter, soft calming music, refreshing clean aesthetic.',
    promptBn: 'শান্ত সবুজ গ্রেডিয়েন্ট, অ্যানিমেটেড মেডিকেল আইকন, বাংলা স্বাস্থ্য টিপস।',
    duration: 15,
    aspectRatio: '1:1',
    tags: ['health', 'tips', 'bangla'],
  },
  // ── ✈️ Travel & Tourism ──────────────────────────────────────────────────
  {
    id: 'sundarban-boat-tour',
    label: 'Sundarban Boat Tour',
    labelBn: 'সুন্দরবন নৌকা ভ্রমণ',
    icon: '🚤',
    category: 'travel',
    categoryBn: 'ভ্রমণ ও পর্যটন',
    prompt: 'Boat gliding through Sundarban mangroves, royal Bengal tiger glimpsed in distance, golden sunset, birds flying, Bengali voice-over: "প্রকৃতির অপরূপ সৌন্দর্য", cinematic drone shot.',
    promptBn: 'সুন্দরবনের ম্যানগ্রোভে নৌকা চলছে, রাজকীয় বাঘ দূরে দেখা যাচ্ছে, সোনালি সূর্যাস্ত।',
    duration: 30,
    aspectRatio: '16:9',
    tags: ['sundarban', 'travel', 'bangla'],
  },
  {
    id: 'cox-bazar-sunset',
    label: 'Cox Bazar Sunset Aeriel',
    labelBn: 'কক্সবাজার সূর্যাস্ত এরিয়াল',
    icon: '🌅',
    category: 'travel',
    categoryBn: 'ভ্রমণ ও পর্যটন',
    prompt: 'Aerial drone shot over Cox Bazar beach at golden hour, waves gently crashing, people walking on sand, Bengali text overlay: "স্বর্গের এক কোণা", cinematic color grading.',
    promptBn: 'সোনালি সময়ে কক্সবাজার সূর্যাস্ত, ড্রোন শট, ঢেউ ভাঙছে, মানুষ হাঁটছে।',
    duration: 20,
    aspectRatio: '16:9',
    tags: ['cox', 'beach', 'bangla'],
  },
  {
    id: 'rattus-temple-tour',
    label: 'Rangpur Rangamati Tour',
    labelBn: 'রাঙামাটি ভ্রমণ',
    icon: '🏔️',
    category: 'travel',
    categoryBn: 'ভ্রমণ ও পর্যটন',
    prompt: 'Panoramic shot of Rangamati hills and lake, indigenous cultural elements, floating market scene, Bengali text: "ভ্রমণপিয়াসিদের স্বর্গ", travel vlog aesthetic.',
    promptBn: 'রাঙামাটির পাহাড় ও হ্রদের প্যানোরামিক শট, ভাসমান বাজার, বাংলা টেক্সট।',
    duration: 30,
    aspectRatio: '16:9',
    tags: ['rangamati', 'travel', 'bangla'],
  },
  // ── 💰 Finance & Crypto ─────────────────────────────────────────────────
  {
    id: 'mobile-banking-tip',
    label: 'Mobile Banking Safety Tips',
    labelBn: 'মোবাইল ব্যাংকিং নিরাপত্তা টিপস',
    icon: '📱',
    category: 'finance',
    categoryBn: 'ফিন্যান্স ও ক্রিপ্টো',
    prompt: 'Smartphone screen animation showing bKash or Nagad app, security tips appearing one by one in Bengali, lock icon animations, green trust color scheme, professional voice-over tone.',
    promptBn: 'স্মার্টফোন স্ক্রিনে বিকাশ/নগদ অ্যাপ, বাংলায় নিরাপত্তা টিপস, লক আইকন অ্যানিমেশন।',
    duration: 30,
    aspectRatio: '9:16',
    tags: ['banking', 'bkash', 'security', 'bangla'],
  },
  {
    id: 'investment-explainer',
    label: 'Investment Basics Explainer',
    labelBn: 'বিনিয়োগ বেসিকস এক্সপ্লেইনার',
    icon: '📈',
    category: 'finance',
    categoryBn: 'ফিন্যান্স ও ক্রিপ্টো',
    prompt: 'Animated graph showing money growing over time, Bengali text overlays explaining compound interest, stock market visuals, professional blue and green color scheme.',
    promptBn: 'অ্যানিমেটেড গ্রাফ — সময়ের সাথে টাকা বাড়ছে, বাংলায় চক্রবৃদ্ধি সুদ ব্যাখ্যা।',
    duration: 45,
    aspectRatio: '16:9',
    tags: ['investment', 'finance', 'bangla'],
  },
  // ── 👰 Wedding & Events ──────────────────────────────────────────────────
  {
    id: 'wedding-invitation-card',
    label: 'Wedding Invitation Card',
    labelBn: 'বিয়ের আমন্ত্রণ কার্ড',
    icon: '💒',
    category: 'wedding',
    categoryBn: 'বিয়ে ও ইভেন্ট',
    prompt: 'Elegant wedding invitation animation, gold and maroon color scheme, Bengali couple name in decorative script, venue and date text animation, soft Bengali wedding music playing.',
    promptBn: 'ঐতিহ্যবাহী বিয়ের আমন্ত্রণ অ্যানিমেশন, সোনা ও মেরুন রঙ, বাংলায় দম্পতির নাম।',
    duration: 15,
    aspectRatio: '9:16',
    tags: ['wedding', 'invitation', 'bangla'],
  },
  {
    id: 'birthday-wish-video',
    label: 'Birthday Wish Video',
    labelBn: 'জন্মদিনের শুভেচ্ছা ভিডিও',
    icon: '🎂',
    category: 'wedding',
    categoryBn: 'বিয়ে ও ইভেন্ট',
    prompt: 'Colorful birthday scene, cake with candles being blown, confetti animation, Bengali text: "জন্মদিনের শুভেচ্ছা!", friends celebrating, warm party lighting.',
    promptBn: 'রঙিন জন্মদিনের দৃশ্য, মোমবাতি জ্বলছে, কনফেটি অ্যানিমেশন, বাংলায় "জন্মদিনের শুভেচ্ছা!"।',
    duration: 15,
    aspectRatio: '1:1',
    tags: ['birthday', 'wish', 'bangla'],
  },
  {
    id: 'mehedi-celebration',
    label: 'Mehedi Celebration Montage',
    labelBn: 'মেহেদি উৎসব মন্টেজ',
    icon: '💚',
    category: 'wedding',
    categoryBn: 'বিয়ে ও ইভেন্ট',
    prompt: 'Close-up of intricately applied mehedi designs on hands, natural henna color, decorative elements, Bengali music, women celebrating in background, warm amber lighting.',
    promptBn: 'হাতে সুন্দর মেহেদি ডিজাইন, প্রাকৃতিক রঙ, সাজসজ্জা, বাংলা মিউজিক, উষ্ণ আলো।',
    duration: 20,
    aspectRatio: '9:16',
    tags: ['mehedi', 'wedding', 'bangla'],
  },
  // ── 📱 Tech & Gadgets ────────────────────────────────────────────────────
  {
    id: 'phone-unboxing-tech',
    label: 'Phone Unboxing Tech Review',
    labelBn: 'ফোন আনবক্সিং টেক রিভিউ',
    icon: '📱',
    category: 'tech',
    categoryBn: 'টেক ও গ্যাজেট',
    prompt: 'Smooth phone unboxing on clean white surface, device revealed with dramatic lighting, accessories laid out neatly, Bengali text overlay specs, tech review aesthetic.',
    promptBn: 'সুন্দর ফোন আনবক্সিং, ডিভাইস ড্রামাটিক লাইটিংয়ে প্রকাশ, অ্যাক্সেসরিজ সাজানো।',
    duration: 20,
    aspectRatio: '9:16',
    tags: ['phone', 'unboxing', 'tech', 'bangla'],
  },
  {
    id: 'app-feature-explainer',
    label: 'App Feature Explainer',
    labelBn: 'অ্যাপ ফিচার এক্সপ্লেইনার',
    icon: '⚡',
    category: 'tech',
    categoryBn: 'টেক ও গ্যাজেট',
    prompt: 'Phone screen recording showing app interface, features highlighted with animated circles and arrows, Bengali feature descriptions appearing, clean tech blue aesthetic.',
    promptBn: 'ফোন স্ক্রিন রেকর্ডিং, অ্যাপ ইন্টারফেস, ফিচার হাইলাইট, বাংলা বিবরণ দেখাচ্ছে।',
    duration: 30,
    aspectRatio: '9:16',
    tags: ['app', 'feature', 'tech', 'bangla'],
  },
  // ── 🌾 Agriculture & Rural BD ────────────────────────────────────────────
  {
    id: 'paddy-harvest-aerial',
    label: 'Paddy Harvest Aerial',
    labelBn: 'ধান কাটার এরিয়াল শট',
    icon: '🌾',
    category: 'agriculture',
    categoryBn: 'কৃষি ও গ্রামীণ বাংলাদেশ',
    prompt: 'Aerial drone shot over golden paddy fields during harvest season, farmers working, golden hour lighting, Bengali text: "মাঠের শুভ্র সোনা", warm cinematic colors.',
    promptBn: 'সোনালি ধানের মাঠের উপর ড্রোন শট, কৃষকরা কাজ করছেন, গোল্ডেন আওয়ার লাইটিং।',
    duration: 20,
    aspectRatio: '16:9',
    tags: ['agriculture', 'paddy', 'rural', 'bangla'],
  },
  {
    id: 'fishing-village-dawn',
    label: 'Fishing Village at Dawn',
    labelBn: 'ভোরে জেলেপল্লা',
    icon: '🐟',
    category: 'agriculture',
    categoryBn: 'কৃষি ও গ্রামীণ বাংলাদেশ',
    prompt: 'Small fishing boats returning to char大姐 িন বন্দর at dawn, nets being pulled, golden light reflecting on water, fishermen silhouetted against sunrise, documentary style.',
    promptBn: 'ভোরে ছোট মাছ ধরার নৌকা ফিরছে, জাল টানছেন জেলেরা, সোনালি আলোয় ছায়া।',
    duration: 20,
    aspectRatio: '16:9',
    tags: ['fishing', 'village', 'dawn', 'bangla'],
  },
  // ── 🎨 Art & Craft ────────────────────────────────────────────────────────
  {
    id: 'pottery-handcraft',
    label: 'Pottery Handicraft Close-Up',
    labelBn: 'মাটির কাজ হ্যান্ডক্রাফট ক্লোজ-আপ',
    icon: '🏺',
    category: 'artcraft',
    categoryBn: 'আর্ট ও কারুশিল্প',
    prompt: 'Close-up of Bengali potter shaping clay on a wheel, hands working the earthenware, natural daylight from window, dust particles floating, documentary aesthetic.',
    promptBn: 'কুমোর মাটি ঘষছেন চাকায়, হাতে মাটির জিনিস তৈরি হচ্ছে, প্রাকৃতিক আলো।',
    duration: 20,
    aspectRatio: '9:16',
    tags: ['pottery', 'handicraft', 'bangla'],
  },
  {
    id: 'alpona-drawing',
    label: 'Alpona Floor Art',
    labelBn: 'আলপনা আঁকা',
    icon: '🎨',
    category: 'artcraft',
    categoryBn: 'আর্ট ও কারুশিল্প',
    prompt: 'Time-lapse of Alpona being drawn on a clean floor with colored rice paste, traditional Bengali patterns and motifs, soft ambient music, warm home lighting.',
    promptBn: 'সময়-বিলুপ্তিতে আলপনা আঁকা হচ্ছে, ঐতিহ্যবাহী বাংলা প্যাটার্ন, উষ্ণ আলো।',
    duration: 30,
    aspectRatio: '16:9',
    tags: ['alpona', 'art', 'bangla'],
  },
]

export const TEMPLATE_CATEGORIES = [
  { id: 'facebook-shop',   name: 'Facebook Shop Ads',   nameBn: 'ফেসবুক শপ বিজ্ঞাপন',    icon: '🛍️' },
  { id: 'education',       name: 'Educational Content', nameBn: 'শিক্ষা কন্টেন্ট',           icon: '📚' },
  { id: 'religious',       name: 'Religious & Spiritual',nameBn: 'ধর্মীয় ও আধ্যাত্মিক',       icon: '🕌' },
  { id: 'food',            name: 'Recipe & Food',        nameBn: 'রেসিপি ও ফুড',            icon: '🍳' },
  { id: 'business',        name: 'Business & Marketing',  nameBn: 'ব্যবসা ও মার্কেটিং',        icon: '💼' },
  { id: 'entertainment',   name: 'Entertainment & Meme', nameBn: 'বিনোদন ও মিম',             icon: '🎭' },
  { id: 'fitness',         name: 'Fitness & Health',      nameBn: 'ফিটনেস ও স্বাস্থ্য',         icon: '🏋️' },
  { id: 'travel',          name: 'Travel & Tourism',     nameBn: 'ভ্রমণ ও পর্যটন',            icon: '✈️' },
  { id: 'finance',         name: 'Finance & Crypto',      nameBn: 'ফিন্যান্স ও ক্রিপ্টো',      icon: '💰' },
  { id: 'wedding',         name: 'Wedding & Events',     nameBn: 'বিয়ে ও ইভেন্ট',            icon: '👰' },
  { id: 'tech',            name: 'Tech & Gadgets',        nameBn: 'টেক ও গ্যাজেট',             icon: '📱' },
  { id: 'agriculture',     name: 'Agriculture & Rural BD',nameBn: 'কৃষি ও গ্রামীণ বাংলাদেশ',   icon: '🌾' },
  { id: 'artcraft',        name: 'Art & Handicraft',       nameBn: 'আর্ট ও কারুশিল্প',          icon: '🎨' },
]

export function getTemplatesByCategory(categoryId: string): VideoTemplate[] {
  return VIDEO_TEMPLATES.filter(t => t.category === categoryId)
}

export function getTemplateById(id: string): VideoTemplate | undefined {
  return VIDEO_TEMPLATES.find(t => t.id === id)
}
