#!/usr/bin/env python3
"""
HOSTAMAR FACEBOOK AUTO-POSTER
==============================
Posts content to Facebook Pages and Groups via the Meta Graph API.

Requires: FB_PAGE_ID, FB_ACCESS_TOKEN env vars (loaded from .env automatically).

Usage:
  python3 scripts/fb-poster.py --post-all       Post all FB content from marketing-output/
  python3 scripts/fb-poster.py --test            Test connection to Facebook API
  python3 scripts/fb-poster.py --post FILE       Post a specific file
  python3 scripts/fb-poster.py --group GROUP_ID  Post launch post to a specific group
  python3 scripts/fb-poster.py --check-token     Validate your access token
"""

import os
import sys
import json
import time
import logging
from datetime import datetime

# ---------------------------------------------------------------------------
# Try to load .env automatically (optional dependency)
# ---------------------------------------------------------------------------
try:
    from dotenv import load_dotenv
    # Look for .env in project root (two levels up from scripts/)
    env_path = os.path.join(os.path.dirname(__file__), "..", ".env")
    if os.path.exists(env_path):
        load_dotenv(env_path)
        print(f"  ✅ Loaded environment from: {env_path}")
    else:
        # Also check the user's home directory
        home_env = os.path.expanduser("~/hostamar-local/.env")
        if os.path.exists(home_env):
            load_dotenv(home_env)
            print(f"  ✅ Loaded environment from: {home_env}")
except ImportError:
    print("  ℹ️  python-dotenv not installed. Install with: pip install python-dotenv")

import requests

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
FB_PAGE_ID = os.environ.get("FB_PAGE_ID", "")
FB_ACCESS_TOKEN = os.environ.get("FB_ACCESS_TOKEN", "")
FB_GROUP_ID = os.environ.get("FB_GROUP_ID", "")  # Optional default group
GRAPH_API_VERSION = "v19.0"
BASE_URL = f"https://graph.facebook.com/{GRAPH_API_VERSION}/{FB_PAGE_ID}"

# Posts directory (generated by marketing-engine.py / mkt-auto.py)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
POSTS_DIR = os.path.join(PROJECT_ROOT, "marketing-output")
LOGS_DIR = os.path.join(PROJECT_ROOT, "logs")

os.makedirs(LOGS_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(os.path.join(LOGS_DIR, "fb-poster.log"), encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger("fb-poster")


# ---------------------------------------------------------------------------
# Helper Functions
# ---------------------------------------------------------------------------
def read_post(filename):
    """Read a post from the marketing-output directory."""
    filepath = os.path.join(POSTS_DIR, filename)
    if not os.path.exists(filepath):
        log.error(f"  ❌ File not found: {filepath}")
        return None
    with open(filepath, "r", encoding="utf-8") as f:
        return f.read().strip()


def check_token():
    """Validate the current access token and show token info."""
    if not FB_ACCESS_TOKEN:
        log.error("  ❌ FB_ACCESS_TOKEN is not set")
        return False

    url = f"https://graph.facebook.com/{GRAPH_API_VERSION}/debug_token"
    params = {
        "input_token": FB_ACCESS_TOKEN,
        "access_token": FB_ACCESS_TOKEN  # App token or same token
    }
    try:
        resp = requests.get(url, params=params, timeout=10)
        data = resp.json()
        if resp.status_code == 200 and "data" in data:
            d = data["data"]
            print(f"""
  Token type:       {d.get('type', 'N/A')}
  App ID:           {d.get('app_id', 'N/A')}
  Application:      {d.get('application', 'N/A')}
  User ID:          {d.get('user_id', 'N/A')}
  Issued at:        {datetime.fromtimestamp(d.get('issued_at', 0)).strftime('%Y-%m-%d %H:%M:%S') if d.get('issued_at') else 'N/A'}
  Expires at:       {datetime.fromtimestamp(d.get('expires_at', 0)).strftime('%Y-%m-%d %H:%M:%S') if d.get('expires_at') and d['expires_at'] != 0 else 'Never (long-lived token)'}
  Scopes:           {', '.join(d.get('scopes', ['N/A']))}
  Valid:            {d.get('is_valid', False)}
  Granular scopes:  {', '.join(d.get('granular_scopes', [])) if d.get('granular_scopes') else 'N/A'}
            """)
            return d.get("is_valid", False)
        else:
            log.error(f"  ❌ Token validation failed: {resp.text[:300]}")
            return False
    except Exception as e:
        log.error(f"  ❌ Exception during token check: {e}")
        return False


def post_to_facebook(message, page_id=None, access_token=None):
    """Post a text message to a Facebook Page feed.

    Args:
        message: Text content to post.
        page_id: Override page ID (defaults to FB_PAGE_ID).
        access_token: Override token (defaults to FB_ACCESS_TOKEN).

    Returns:
        Post ID string on success, None on failure.
    """
    pid = page_id or FB_PAGE_ID
    tok = access_token or FB_ACCESS_TOKEN

    if not pid or not tok:
        log.warning("  ⚠️  FB_PAGE_ID or FB_ACCESS_TOKEN not configured.")
        log.info(f"  📝 Message saved (not posted): {message[:60]}...")
        return None

    url = f"https://graph.facebook.com/{GRAPH_API_VERSION}/{pid}/feed"
    payload = {
        "message": message,
        "access_token": tok,
    }

    for attempt in range(3):  # Retry up to 3 times
        try:
            resp = requests.post(url, data=payload, timeout=15)
            if resp.status_code == 200:
                post_id = resp.json().get("id", "unknown")
                log.info(f"  ✅ Posted! ID: {post_id}")
                return post_id
            elif resp.status_code == 400:
                error_data = resp.json().get("error", {})
                error_msg = error_data.get("message", "Unknown error")
                error_code = error_data.get("code", 0)
                error_subcode = error_data.get("error_subcode", 0)

                # Handle specific errors
                if error_code == 190:
                    log.error(f"  ❌ Token validation error: {error_msg}")
                    log.error("     → Your access token is invalid or expired.")
                    log.error("     → Regenerate it at: https://developers.facebook.com/tools/debug/accesstoken")
                elif error_code == 200:
                    log.error(f"  ❌ Permission error: {error_msg}")
                    log.error("     → Make sure your token has 'pages_manage_posts' and 'pages_read_engagement' permissions.")
                elif error_code == 100 and error_subcode == 33:
                    log.error(f"  ❌ URL or content not allowed: {error_msg}")
                elif error_code == 368:
                    log.error(f"  ❌ Rate limited: {error_msg}")
                    if attempt < 2:
                        wait = 60 * (attempt + 1)
                        log.info(f"     → Waiting {wait}s before retry...")
                        time.sleep(wait)
                        continue
                elif error_code == 100 and "message" in error_msg.lower() and "required" in error_msg.lower():
                    log.error(f"  ❌ Missing required field: {error_msg}")
                else:
                    log.error(f"  ❌ Error {resp.status_code} (code={error_code}, subcode={error_subcode}): {error_msg}")
                return None
            else:
                log.error(f"  ❌ HTTP {resp.status_code}: {resp.text[:300]}")
                return None
        except requests.exceptions.Timeout:
            log.warning(f"  ⏱️  Timeout on attempt {attempt + 1}/3")
            if attempt < 2:
                time.sleep(5)
                continue
            log.error("  ❌ Request timed out after 3 attempts")
            return None
        except requests.exceptions.ConnectionError as e:
            log.error(f"  ❌ Connection error: {e}")
            return None
        except Exception as e:
            log.error(f"  ❌ Exception: {e}")
            return None

    return None


def post_to_group(group_id, message, access_token=None):
    """Post a text message to a Facebook Group feed.

    Note: The access token must have the groups_access_member_info
    or publish_to_groups permission, and you must be a member of the group.
    """
    tok = access_token or FB_ACCESS_TOKEN

    if not group_id or not tok:
        log.warning("  ⚠️  GROUP_ID or FB_ACCESS_TOKEN not provided.")
        return None

    url = f"https://graph.facebook.com/{GRAPH_API_VERSION}/{group_id}/feed"
    payload = {
        "message": message,
        "access_token": tok,
    }

    try:
        resp = requests.post(url, data=payload, timeout=15)
        if resp.status_code == 200:
            post_id = resp.json().get("id", "unknown")
            log.info(f"  ✅ Group {group_id} posted! ID: {post_id}")
            return post_id
        else:
            log.error(f"  ❌ Group {group_id}: HTTP {resp.status_code} — {resp.text[:300]}")
            return None
    except Exception as e:
        log.error(f"  ❌ Exception for group {group_id}: {e}")
        return None


def post_with_photo(message, photo_path, page_id=None, access_token=None):
    """Post a message with a photo to a Facebook Page.

    Args:
        message: Text content.
        photo_path: Local path to an image file.
        page_id: Override page ID.
        access_token: Override token.

    Returns:
        Post ID on success, None on failure.
    """
    pid = page_id or FB_PAGE_ID
    tok = access_token or FB_ACCESS_TOKEN

    if not pid or not tok:
        log.warning("  ⚠️  FB_PAGE_ID or FB_ACCESS_TOKEN not configured.")
        return None

    if not os.path.exists(photo_path):
        log.error(f"  ❌ Photo not found: {photo_path}")
        return None

    url = f"https://graph.facebook.com/{GRAPH_API_VERSION}/{pid}/photos"
    try:
        with open(photo_path, "rb") as img:
            files = {"source": img}
            data = {"message": message, "access_token": tok}
            resp = requests.post(url, files=files, data=data, timeout=30)

        if resp.status_code == 200:
            post_id = resp.json().get("id", "unknown")
            log.info(f"  ✅ Posted with photo! ID: {post_id}")
            return post_id
        else:
            log.error(f"  ❌ Photo post error: {resp.status_code} — {resp.text[:300]}")
            return None
    except Exception as e:
        log.error(f"  ❌ Exception posting photo: {e}")
        return None


def auto_post_all():
    """Find and post all fb_*.txt files in marketing-output/."""
    if not os.path.exists(POSTS_DIR):
        log.error(f"  ❌ Posts directory not found: {POSTS_DIR}")
        log.info("     Run mkt-auto.py or marketing-engine.py first to generate posts.")
        return

    fb_files = sorted(
        [f for f in os.listdir(POSTS_DIR) if f.startswith("fb_") and f.endswith(".txt")]
    )

    if not fb_files:
        log.warning("  ⚠️  No fb_*.txt files found in marketing-output/")
        log.info("     Generate them first with: python3 mkt-auto.py")
        return

    log.info(f"  📤 Found {len(fb_files)} Facebook posts to publish\n")

    results = []
    for fb_file in fb_files:
        message = read_post(fb_file)
        if message is None:
            results.append((fb_file, False))
            continue

        log.info(f"  📝 Publishing: {fb_file}")
        success = post_to_facebook(message)
        results.append((fb_file, success is not None))

        if success:
            log_line = f"{fb_file}|success|{success}\n"
            with open(os.path.join(LOGS_DIR, "fb-posted.log"), "a", encoding="utf-8") as logfile:
                logfile.write(log_line)
        else:
            log_line = f"{fb_file}|failed\n"
            with open(os.path.join(LOGS_DIR, "fb-posted.log"), "a", encoding="utf-8") as logfile:
                logfile.write(log_line)

        time.sleep(3)  # Rate-limit safety between posts

    # Summary
    posted = sum(1 for _, s in results if s)
    failed = sum(1 for _, s in results if not s)
    log.info(f"\n{'='*50}")
    log.info(f"  📊 Results: {posted}/{len(results)} posted | {failed} failed")
    log.info(f"{'='*50}")

    return results


def post_single_file(filename):
    """Post a single file from marketing-output/."""
    if not filename.endswith(".txt"):
        filename += ".txt"

    message = read_post(filename)
    if message is None:
        available = [f for f in os.listdir(POSTS_DIR) if f.startswith("fb_")]
        if available:
            log.info("  Available files:")
            for f in available:
                log.info(f"    - {f}")
        return

    log.info(f"  📝 Publishing: {filename}")
    post_to_facebook(message)


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------
def main():
    print(f"\n{'='*60}")
    print(f"  🚀 HOSTAMAR FACEBOOK AUTO-POSTER")
    print(f"  📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'='*60}\n")

    # Show config status
    print(f"  📋 Configuration:")
    print(f"     FB_PAGE_ID:       {'✅ Set' if FB_PAGE_ID else '❌ Missing'}")
    print(f"     FB_ACCESS_TOKEN:  {'✅ Set (' + FB_ACCESS_TOKEN[:10] + '...)' if FB_ACCESS_TOKEN else '❌ Missing'}")
    print(f"     Posts directory:  {POSTS_DIR}")
    print(f"     Log file:         {os.path.join(LOGS_DIR, 'fb-poster.log')}\n")

    if not FB_PAGE_ID or not FB_ACCESS_TOKEN:
        log.warning("  ⚠️  FB_PAGE_ID and FB_ACCESS_TOKEN must be set in .env file.")
        log.info("     See FACEBOOK-API-SETUP.md for setup instructions.\n")

    if len(sys.argv) < 2:
        print("  Usage:")
        print("    python3 scripts/fb-poster.py --post-all        Post all FB content")
        print("    python3 scripts/fb-poster.py --test            Test Facebook API connection")
        print("    python3 scripts/fb-poster.py --post FILE       Post a specific file")
        print("    python3 scripts/fb-poster.py --group GROUP_ID  Post to a specific group")
        print("    python3 scripts/fb-poster.py --check-token     Validate your access token")
        print("    python3 scripts/fb-poster.py --photo PATH      Post a single photo with message")
        print()
        return

    command = sys.argv[1]

    if command == "--post-all":
        auto_post_all()

    elif command == "--test":
        print("  🧪 Testing Facebook API connection...\n")
        # First check the token
        token_valid = check_token()
        if not token_valid:
            log.warning("  ⚠️  Token validation failed but trying a test post anyway...\n")

        # Try to post a test message
        test_msg = (
            "🔄 Test post from Hostamar Automation System\n"
            "If you see this, the Facebook API connection is working!\n"
            f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            "#Hostamar #Test"
        )
        result = post_to_facebook(test_msg)
        if result:
            log.info(f"\n  ✅ Facebook API connection is WORKING! (Post ID: {result})")
            # Delete the test post
            try:
                del_url = f"https://graph.facebook.com/{GRAPH_API_VERSION}/{result}"
                requests.delete(del_url, params={"access_token": FB_ACCESS_TOKEN}, timeout=10)
                log.info("  🧹 Test post deleted.")
            except Exception:
                pass
        else:
            log.error("\n  ❌ Facebook API connection FAILED.")

    elif command == "--post":
        if len(sys.argv) < 3:
            log.error("  ❌ Please specify a filename (e.g., fb_P001_launch.txt)")
            return
        post_single_file(sys.argv[2])

    elif command == "--group":
        if len(sys.argv) < 3:
            log.error("  ❌ Please specify a Group ID")
            return
        group_id = sys.argv[2]
        msg = read_post("fb_P001_launch.txt")
        if msg is None:
            # Fallback to a generic message
            msg = "🚀 Check out Hostamar.com — AI Video Generation for Bangladesh Creators! 🇧🇩\n\nhttps://hostamar.com"
        post_to_group(group_id, msg)

    elif command == "--check-token":
        check_token()

    elif command == "--photo":
        if len(sys.argv) < 3:
            log.error("  ❌ Please specify a photo path")
            return
        photo_path = sys.argv[2]
        message = read_post("fb_P001_launch.txt") or "🚀 Hostamar.com — AI Video Generation for Bangladesh! 🇧🇩\n\nhttps://hostamar.com"
        post_with_photo(message, photo_path)

    else:
        log.error(f"  ❌ Unknown command: {command}")
        sys.exit(1)


if __name__ == "__main__":
    main()
